[package]
name = "netmon-core"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
regex = "1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
rusqlite = { version = "0.31", features = ["bundled"] }
dirs = "5"
ureq = { version = "2", default-features = false, features = ["tls"] }
maxminddb = "0.30.0"
flate2 = "1.1.9"

[dev-dependencies]
